apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      protocol: TCP
      port: 1025   # Port for SMTP
      targetPort: 1025
    - name: http
      protocol: TCP
      port: 8025   # Port for HTTP (Web UI)
      targetPort: 8025
