apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: node-service
  name: node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.service: node-service
    spec:
      containers:
        - image: drew138/architecture-node-ambassador:v4
          name: node-service
          ports:
            - name: http-server 
              containerPort: 8000
          env:
            - name: DB_HOST
              value: db
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: node-credentials
                  key: stripe_secret
            - name: CHECKOUT_URL
              value: http://localhost:5000/
            - name: BROKER_KAFKA
              value: pkc-12576z.us-west2.gcp.confluent.cloud:9092
            - name: USERNAME_KAFKA
              valueFrom:
                secretKeyRef:
                  name: node-credentials
                  key: kafka_username
            - name: PASSWORD_KAFKA
              valueFrom:
                secretKeyRef:
                  name: node-credentials
                  key: kafka_password
          resources:
            limits: # Set the memory limit for the container
              cpu: "500m"     # Set the CPU limit for the container (0.5 CPU cores)
            requests:
              memory: "300Mi" # Set the initial memory request for the container
              cpu: "200m"
      restartPolicy: Always
