apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: node-service
  name: node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.service: node-service
    spec:
      containers:
        - image: drew138/architecture-node-ambassador:v1
          name: node-service
          ports:
            - name: http-server 
              containerPort: 8000
          env:
            - name: DB_HOST
              value: db
            - name: STRIPE_SECRET
              value: sk_test_51P4tXiIdhZFpJSS67BlVW5AeoxPK1b4aPZfht0SU3JNpJIJMwoO6JovJ3zr1khKekmHjxYrHSUV18qqD3JhUuDol00DstyH7X9
            - name: CHECKOUT_URL
              value: http://localhost:5000/
            - name: BROKER_KAFKA
              value: pkc-12576z.us-west2.gcp.confluent.cloud:9092
            - name: USERNAME_KAFKA
              value: RHJCYBSF3FMIKKJQ
            - name: PASSWORD_KAFKA
              value: wBs6Af4l1xB47gOlllgwchFlnIU0LpVjpxC+AyeZyZwdIPx+Qvh3NWhY3eZ7+q0m
      restartPolicy: Always
