apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: node-service
  name: node-service
spec:
  ports:
    - port: 8002
      targetPort: http-server
  selector:
    io.kompose.service: node-service
  type: LoadBalancer
