apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-claim-auth
  name: db-claim-auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
