apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: auth-ms
  name: auth-ms
spec:
  selector:
    matchLabels:
      io.kompose.service: auth-ms
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/auth-microservice-default: "true"
        io.kompose.service: auth-ms
    spec:
      containers:
        - image: drew138/auth-microservice:v1
          name: auth-ms
          ports:
            - name: http-server 
              containerPort: 8000
          env:
            - name: DB_HOST
              value: db
            - name: SECRET_KEY
              value: secret
          resources:
            limits:
              memory: "500Mi"   # Set the memory limit for the container
              cpu: "400m"     # Set the CPU limit for the container (0.5 CPU cores)
            requests:
              memory: "300Mi" # Set the initial memory request for the container
              cpu: "200m" 
      restartPolicy: Always
