apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: front-service
  name: front-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.service: front-service
    spec:
      containers:
        - image: drew138/react-ambassador:v12
          name: front-service
          ports:
            - name: http-server 
              containerPort: 3000
          resources:
            limits: # Set the memory limit for the container
              cpu: "500m"     # Set the CPU limit for the container (0.5 CPU cores)
            requests:
              memory: "500Mi" # Set the initial memory request for the container
              cpu: "200m"
      restartPolicy: Always
