apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: user-ms
  name: user-ms
spec:
  ports:
    - port: 8001
      targetPort: http-server
  selector:
    io.kompose.service: user-ms
  type: LoadBalancer
