apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: user-ms
  name: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-ms
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.service: user-ms
    spec:
      containers:
        - image: drew138/user-microservice
          name: user-ms
          ports:
            - name: http-server 
              containerPort: 8000
          env:
            - name: DB_HOST
              value: db
      restartPolicy: Always
